### ISSUE TITLE
RSPDX Bandwidth

### ISSUE THREAD

**Issue by Mfallon100** [softsyst/qirx_issues#114]
Hi Clem, I'm using a RSPDX. Would it be possible to allow narrower bandwidth please, preferably user adjustable like for the RTL-SDR.? When conditions are very good I am getting qirx displaying MUX's on adjacent blocks.

Many thanks

**Comment by softsyst** [comment]
Please explain in more detail. Are your "muxes" DAB muxes? In that case a smaller bandwidth than about 1.6MHz as is delivered from the RSPs, makes no sense, as DAB needs at least 1.6MHz. If you select in qirx a sampling rate of 2048000, you see on the display a total bandwidth of 2.048MHz, which the RSP internally limits to 1.536 MHz, which is optimal for DAB. 
Additionally, if you need to limit your bandwidth further, you can use the Filter which qirx offers on its GUI. However, this limits the samples after they passed the receiver and had entered the qirx software.

Clem

**Comment by MikeFallon** [comment]
Thanks. I probably didn't explain myself very well. For example if I have two strong MUXes -  MUX 1 on 5A and MUX 2 on 5B, as the software scans some passes will display MUX 1 on 5B or MUX 2 on 5A. I had assumed that RSP was using 2MHz+ bandwidth but from your explanation the RSP limits to ~1.5MHz so that is not the problem. When I was using an RTL-SDR this didn't seem to happen so often as I would sometimes limit the b/w to 1.4MHz.
Thanks

**Comment by softsyst** [comment]
Scanning is a different issue. Sometimes it happens that scans get neighboring muxes due to timing conditions. If you want to avoid it, try to increase the "before" and "after" times in the scan dialog.
With respect to the bandwidth, you might wish to reduce the bandwidth by the qirx filter, settable on the GUI, as I mentioned in my last post.
Reducing the bandwidth in the RSP tuner in a similar way than in the RTL-SDRs  is not possible.

**Comment by MikeFallon** [comment]
Thanks for the explanation Clem
