### ISSUE TITLE
RSPDX Connection Issues

### ISSUE THREAD

**Issue by MikeFallon** [softsyst/qirx_issues#121]
Hi Clem,

I'm having some connection issues with my RSPDX, I'm using v4.1.2. When trying to start the RX I get a pop up stating "Connect to 127.0.0.1:1236 (or 1234) failed after 1 attempt". I have swapped USB ports and rebooted my PC but I can't get it to connect again. I have also reinstalled the SDRplay API.

Could you please advise.

Thanks

Mike

**Comment by superblyb** [comment]
I also expierenced this behaviour several times. After I reset qirx to its default values or after a fresh install, this problem had disappeared.
Maybe this issue was also related to the number of connected devices and the herefor settings.

**Comment by softsyst** [comment]
Hello Mike,

sorry you are having problems. However, the first things you should do is to follow the steps on my website
[https://qirx.softsyst.com/QIRXInstall](url), and try the steps in the last paragraph
"What could be done if Step 9 above does not give the desired result."

Your error message can have a number of causes, what you describe is too general to be able to help. Please try in particular

- to start RSP3_tcp manually (uncheck autostart and autostop in the Settings)
- make screenshots and send them to me or here to this page, as described on the mentioned website.
- Try a short and possibly detailed description since when you have the problem, and if there was some particular event causing it. Such things usually do not happen "out of the blue".

Thanks, and regards,

Clem

**Comment by superblyb** [comment]
The link above  gives me an error. It should probably be

https://qirx.softsyst.com/QIRXInstall

**Comment by MikeFallon** [comment]
Thank you very much Clem. It seems that somehow my Microsoft Access Database Engine had disappeared. Reinstalled it and all OK.

Thanks again

Regards,
Mike

**Comment by softsyst** [comment]
Thanks for info, Mike. This is strange, as also others reported that the DB driver had disappeared. I'll have a view at the effort to check the DB driver presence on startup in the program.
I assume I can close that one now.

@superblyb
Thanks Hans, for your correction. It was already rather late yesterday...
