### ISSUE TITLE
Lost SPI logos for the 4 DLF services and Schlagerparadies

### ISSUE THREAD

**Issue by edd-cgfan** [softsyst/qirx_issues#125]
Hi Clem,

Did you notice that the above mentioned logos are no longer displayed ?
I only saw it when I tested the new version.
They **are** in the SPI Temp folder. However, they don't get into the respective folders.

Yesterday I played around with them and copied the ones for DLF to the respective folders:
After some time they disappear.
Then I copied a self-made image for a private station over here (Radio SAW) and it seems that it stays there.

It has been mentioned here:
[Re: Sammelstelle für DAB+-Bundesmuxx Programm-Störungen](https://www.rundfunkforum.de/viewtopic.php?p=1735152#p1735152)

Here is a screenshot from today:
![5C-BUMUX1-Missing-Images](https://github.com/softsyst/qirx_issues/assets/49753409/89bda655-00e9-4d94-af34-c7d53ee7dce7)

BTW: Thank you Clem: I really like the listing of channel names on the TII tab, as shown in the screenshot above.

Regards,
cgfan

**Comment by softsyst** [comment]
Hi cgfan,

Yes, I did, and spent some time to investigate it. BTW, you are the first one to notice. The logo files are all received, but the meta information, being contained in an .EIB file, is not. There, the station Ids are all four listed, but the necessary picture information is not. Without this info no assignment of the files to the service is possible. DLF and friends are the only services where this info is missing in the .EIB file. This fact cannot be a problem of interpretation, because the .EIB is a binary file just "received as is". The corresponding xml file is created later and reflects the same fact. The info is already missing in the binary file.

The issue did not show up earlier, therefore the entries in the posting you mention is diffuse. BTW, thanks for the link, I didn't know it yet. Let me explain:
In Issue #119 there was a request to update logos if a new on shows up. This seemed easier as it was. The realization has to collect all of the logos, then delete the present logos, and copy the new ones into the Pool and the ensemble directories. With this solution the new **hr logos** all showed up. And the DLF logos were gone, because the received pictures could not be assigned.

The problem with #119 was that the new logos were collected and added, but the old ones remained, so the showing up of the new logo was random. For DLf, this meant that the old logos were never deleted, masking the problem.

I had expected they made some maintenance and the logos will appear again, but the situation did not change since at least one or two weeks. The procedure to collect all the logos did not change at all.
The mentioned .EIB file contains all the other logos of 5C, and additionally the logos of 9B, all except the newly missing ones are there. No idea why.
We had some time ago a very similar issue with the BBC (I think it was #72). There, all was collected half an hour long, but no logos appeared, and it turned out that the transmission of the MOT directory was not complete. Then, the following day all was ok again.

When you notice that your selfmade image pertains, did you wait until all MOT in 5C was collected, i.e. the green lamps stopped flashing?? This lasts currently about 10 minutes.

The additional strange thing is that the DLF EPG info is all there, being collected in the same sequence.
Maybe some hidden bug, either in qirx or the DLF. Who knows.

Regards,

Clem

**Comment by edd-cgfan** [comment]
Thanks for the explanation. Interesting.

You are right:
> When you notice that your selfmade image pertains, did you wait until all MOT in 5C was collected, i.e. the green lamps stopped flashing?? This lasts currently about 10 minutes.

I hadn't waited long enough. The images are gone again...

Regards,
cgfan

**Comment by softsyst** [comment]
News from "SCHLAGERPARADIES":
They seem to like the capital letters. But not everywhere. In the "Content" field of the MOT objects, the use lower case for their filenames of png pictures, in the EIB file they use uppercase for the same info. QIRX searches the EIB name in the MOT Content and compares both, and voilá this only works when both are lowercase or both uppercase, but not mixed. After correction to an all-lowercase compare their logos appear.

On the other hand, the missing DLF files are very probably due to the missing entry in the .EIB files, as described above.

**Comment by edd-cgfan** [comment]
Hi Clem,

Just noticed:
All the SPI logos are back again with version 4.1.3:

![5C-All-SPI-Logos](https://github.com/softsyst/qirx_issues/assets/49753409/558a7ad7-4559-4c9b-9b76-5c426b718cfd)

BTW: I wrote to DLF Hoererservice on November 30th. I hope that my letter has triggered the correction...

Regards,
cgfan

**Comment by softsyst** [comment]
Hi cgfan,

thanks for the info and your activity. I had done likewise, to Media Broadcast, on December 1. They answered on Dec 4:

"Ihre Anfrage wurde an die zuständige Fachabteilung weitergeleitet und wird von einem Techniker geprüft. Im Anschluss kommen wir wieder auf Sie zu.

Bis dahin bitten wir Sie um ein wenig Geduld."

Although nothing else happened, obviously our activities worked! The .EIB file again contains the necessary info.

Regards,
Clem

**Comment by edd-cgfan** [comment]
Nice to hear that.
I chose DLF Hoererservice because I've had good experiences with it in the past and it seams that the messages do not end up in the trash immediately: At first you only get an automatic reply. Some time later you see a result or get an answer from an author. For example, this is how I got in touch with the DLF correspondent for Saxony-Anhalt, who replied like this:
"... über Umwege hat mich Ihre Nachricht erreicht...."

Regards,
cgfan

**Comment by softsyst** [comment]
Schlagerparadies issue should be fixed in 4.2.1

**Comment by edd-cgfan** [comment]
Looks fine here:
I renamed the "old" SPI folder and had it recreated. This is the result:
![5C-SPI-All+_V421_](https://github.com/softsyst/qirx_issues/assets/49753409/2628d50f-87fb-4b07-ac4d-71d7ad1aa1d2)

Regards and Happy New Year,
cgfan

**Comment by softsyst** [comment]
Thanks for feedback! 
I close this issue.

Und auch ein Gutes Neues!!
