### ISSUE TITLE
Request: screenshots

### ISSUE THREAD

**Issue by WIHDIA** [softsyst/qirx_issues#14]
Wouldn't it be easy to have a screenshot button at the top?

**Comment by softsyst** [comment]
No, it wouldn't. Because it is much easier to press Alt+PrtScrn, the built-in possibility in Windows. This will not be realized. Alt+PrtScrn puts your selected Window on the Windows clipboard, from where it can be directly be imported via Ctrl+V into the imaging app of your choice.
I suggest to close this one

**Comment by WIHDIA** [comment]
OK.  I do use Alt+PrintScreen. No problem. One-click button like in SDRC has some value and ease of use though.
