### ISSUE TITLE
RTL_TCP on a external device (raspberry) not working. v 3.2.3

### ISSUE THREAD

**Issue by jpuigs** [softsyst/qirx_issues#147]
I had version 3.2.2 and it was working.
I've decided to update to 3.2.3 and I can't get it working anymore...
Besides, it mixes port 1234 with 1235
![image](https://github.com/softsyst/qirx_issues/assets/44906458/6ea78db4-81fa-4739-9e87-34478d64a5e8)

![image](https://github.com/softsyst/qirx_issues/assets/44906458/c68eaefd-85a0-49ff-afd5-c108480b6009)

![image](https://github.com/softsyst/qirx_issues/assets/44906458/e226091d-3de7-4bab-85ab-d1229ee9bfc7)

**Comment by softsyst** [comment]
No, it does not mix anything. 1235 is (since long) the port for a back-channel from the rtl_tcp, which your rtl_tcp obviously does not service. You should use the rtl_tcp from @old-dab's Github site for your raspi. The back-channel port always is one more than the forward-channel port, 1234 in your case.

**Comment by jpuigs** [comment]
But why it was working in V 3.2.2  ?
I saw it today, just before uninstalling and installing 3.2.3

**Comment by softsyst** [comment]
There were changes in the 3.2.3: The rtl_tcp does not work any more, what is needed is the rtl2_tcp, working on Windows or Linux. QIRX offers a selection of devices if more than one is connected. However, if only one is connected, the serial has to be reported back also, what is not provided by the rtl_tcp. In the case of three devices connected, it looks like so (the tile is of course a misnomer)
![image](https://github.com/softsyst/qirx_issues/assets/51386375/1f90f967-93d5-4217-b829-7d1cefce96b9)

You have the following options:
1. Continue like before with the 3.2.2 and rtl_tcp on your raspi
2. Use the 3.2.3 and the rtl2_tcp on the raspi. This has the disadvantage that other apps will not run any more, as they usually won't cooperate with the rtl2_tcp. For other apps using the rtl_tcp, the rtl_tcp could be started additionally listening at another port, like 2234, the port selection goes with the -p option. Not tested though, but it should work.
3. Use the V4, which offers in QIRX to select two drivers, the old rtl_tcp or the rtl2_tcp. This was introduced on user requests, due to the mentioned disadvantage of 2.

Hope this helps.

**Comment by jpuigs** [comment]
Thank's, but  I can't find 3.2.2 anywhere....

**Comment by softsyst** [comment]
> Thank's, but I can't find 3.2.2 anywhere....

Not nice, but not an issue of QIRX. I close this one. If you need the 3.2.2, send me a PM, I'll send you a link.
