### ISSUE TITLE
EPG logos from 5C not shown after reception

### ISSUE THREAD

**Issue by nona00** [softsyst/qirx_issues#151]
When receiving the dab ensemble 5C the logos from EPG Deutschland are not shown in the station selection after reception. In the temp folder the pictures are visible

![grafik](https://github.com/softsyst/qirx_issues/assets/3192606/ac3f6cda-2718-4e8c-b0c3-453a52a93ff0)

![grafik](https://github.com/softsyst/qirx_issues/assets/3192606/0f64f541-47bd-4652-aedd-d198e62bcb29)

QIRX 4.2.1 on Windows 10 22H2

**Comment by nona00** [comment]
after waiting a long time the logos were shown.

But the .EIB file was removed after a while. Why it is removed?

![grafik](https://github.com/softsyst/qirx_issues/assets/3192606/e008f66c-fe35-41f2-8f0a-ddb077eaf109)

It would be great if there would be a a progress status or log for epg reception and the possibility to view the logos in all sizes.

**Comment by softsyst** [comment]
hi nona00,

your questions: 
- Waiting time 5C: The 5C SPI transmission time currently is at about 10 minutes. They transmit not only all the logos of the 5C, but also many others, together with EPG info.

- EIB removal: The EIB is a binary file usually of no importance for the users. The info of the EIB is transformed into a xml file. All other transient files like the .EHB are deleted as well, in order not to pollute the user's disk with all of this information.

- Logo size: If you tune to a service, you can see its large-sized logo in the DAB "Services" tab.

- missing progress bar: This is not possible, as the information being sent is usually not known in advance. This is different from e.g. the SLS pictures, where a progress bar is provieded.

- status: Status info exists. It is the two blinking green "lamps". The blinking stops as soon as the collected SPI info is complete.

Hope this helps,
Clem

**Comment by nona00** [comment]
Thank you Clem for your explanations.

I see that the EIB is not relevant for normal users, but for getting more in details it is needed. For 5C it has only a size of 10kb, so it is not significant if the file stays there.

The blinking green lamps are a good hint, but more detailed information what file is currently received would be great. Would it be possible to do the progress status based on the items which are referenced in the EIB file?

**Comment by softsyst** [comment]
Hi nona00,

Sorry for the long delay (vacations).

the size of the EIB file of course is not an issue. I see that it could be useful for special purposes. You could easily get it by observing the SPI temp directory, waiting for the EIB to show up in Win Explorer and copying it to a place of your choice. If it would be copied regularly, there would be another file useless for the vast majority of users. 

The SPI processing is done in the way that all info for a complete "directory" (identified by its Transport Id) is first collected, and then evaluated. Currently, if the directory will never complete (due to an error on the xmitter side, or a bad channel), the collection will continue forever. We already hat such cases (BBC missing information).

The detailed info what file is currently received is not easily obtained, as the files usually consist of different blocks, and the transmission is not "file oriented" in the way that e.g. standard filenames are prescribed. The info what is received is based on "Transport Ids". These can all be inspected when looking at the realtime xml log of qirx, which can be activated at any time, and comfortably viewed and/or filtered with e.g. the free log4view utility. Logging level can be controlled in the "Settings" at any time.
In case you need more info on this, we can continue the discussion here, or you could send me a PM.

Clem

**Comment by softsyst** [comment]
Currently, no action taken here. I close it. If you feel it should be re-opened, please feel free to do so.
