### ISSUE TITLE
Calibrate

### ISSUE THREAD

**Issue by WIHDIA** [softsyst/qirx_issues#22]
When doing a Calibrate you first get a message like this 'Frequency correction (ppm) is not 0, but - ... . Please reset if first.'
After resetting it a new calibration can be done. Would it not be user friendly if this is done automatically? Push calibrate, QIRX then resets ppm to 0 and recalibrates.

73
Herman

**Comment by softsyst** [comment]
Hi Herman,
I hesitate, because it is intended as a reminder that perhaps a set calibration should not be reset. With the new more accurate calibrations it might take a rather long time after a startup or a receiver change to have stable temperature conditions. E.g. the RSPs need about 10-15 minutes even if the remain on power, after startup perhaps double that time.
I'll try to collect more opinions about it.

73,
Clem

**Comment by WIHDIA** [comment]
I see your point, Clem. The time span is indeed to be taken into account!
73
Herman

**Comment by softsyst** [comment]
I close this now. Please re-open if you find it necessary.
