### ISSUE TITLE
DAB MER measurement not found in QIRX 4.0.2

### ISSUE THREAD

**Issue by salvaaod** [softsyst/qirx_issues#52]
Hi, not sure if a bug, I do not find anywhere  the DAB MER measurement in QIRX 4.0.2, I am using a SDR Play receiver. According to the changelog DAB MER  was introduced in 4.0.1. Has this feature been lost ?

Thanks for your help.

Salva

**Comment by softsyst** [comment]
Hi Salva,

thanks for pointing this out. Your are very right, there still is a SNR indicated on the GUI and no MER. The reason is that nobody could tell me for DAB whether there is an accepted method to measure the MER, which I did not expect at all. Also the ETSI papers which refer to this are more than vague. Other "high-end" product descriptions as well are rather quiet in this respect. Companies - when asked - seem to be very cooperative at first contact, and then suddenly are no more.

I am not really decided yet how to proceed, as the "SNR" in QIRX in effect is kind of a MER, because it measures the quality of the modulation. The measurement is done in the way that - if you look into the "linear" Constellation diagram - the deviation of the single dots (I/Q angles) from their expected angle is measured, as the Standard Deviation. This measures the quality of the demodulation or the modulation error. BTW QIRX can do this very nicely because it features an automatic sampling rate correction which is necessary to get "horizontal" and not "oblique" lines in the linear Constellation, ready for this kind of evaluation, also for dongles with high sampling rate errors (many ppm).

Anyway, this should at least mentioned somewhere. In any case, I take your remark as an occasion to make a notice in the next version 4.03, which will come in the not too far future.

Regards,
Clem

**Comment by softsyst** [comment]
4.03 now features MER and CNR. I close this one.
