### ISSUE TITLE
DAB SPI logos not decoded.

### ISSUE THREAD

**Issue by salvaaod** [softsyst/qirx_issues#53]
Hi, I run a small DAB mux and had been using QIRX for testing, now I have added SPI logos and QIRX is not decoding them while other car receivers do.  I am attaching a ETI sample of the mux in case you want to test.
[mux.zip](https://github.com/softsyst/qirx_issues/files/9792279/mux.zip)

**Comment by andimik** [comment]
Did you check the "home" directory? You should find a new directory with the Ensemble Id and all SPI logos.

Is your eti file long enough to decode all files?

**Comment by salvaaod** [comment]
I am testing this off air, so should be ok, the ETI file I included is around 30 sec, should be enough to decode the logos, there is only two stations with logos. There is no "home" directory created over the installation directory. The QIRX is 3.2.2 but I tested over 4.0.2 as well. 

Below is my interface, image, Is there anything further I can test ?

Thanks
Salva

P.S: I have attached a video of the same mux received on a car an the logo being decoded, so, I am sure the logo works in other receivers


![image](https://user-images.githubusercontent.com/26838980/195997485-8fb9e55e-b991-4e0f-9a33-8ae575e3517a.png)


https://user-images.githubusercontent.com/26838980/195997915-fd743940-2ab8-4d98-9876-c0bdcb73a764.mp4

**Comment by softsyst** [comment]
Hi Salva,

Unfortunately, ETI files cannot be read by qirx. What I need is a raw file. Logo decoding sometimes needs some time, so 3 minutes would be good. You could upload it on some dropbox and post the link here.
Apart from this, you could follow @andimiks suggestion and check the directories.

Another help could be a logfile. For this to work, you could enable "Debug" logging in the "Settings" (toothed wheel). You'll find the log usually in the directory C:\qirxLogging.

Thanks for cooperation,

Clem

**Comment by andimik** [comment]
@salvaaod

Maybe you post a longer eti and I will try next week. I am also using odr-dabmod and know how to use cQirx (and Qirx) with a fifo file, so I don't need to create a raw file for that reason.

But your Screenshot shows a very bad reception (SNR bar is red). Please note that Qirx needs an error-free reception in order to display these files.

**Comment by andimik** [comment]
Or you post the `output.dat` then I can insert it into a dummy mux.

**Comment by salvaaod** [comment]
> @salvaaod
> 
> Maybe you post a longer eti and I will try next week. I am also using odr-dabmod and know how to use cQirx (and Qirx) with a fifo file, so I don't need to create a raw file for that reason.
> 
> But your Screenshot shows a very bad reception (SNR bar is red). Please note that Qirx needs an error-free reception in order to display these files.

Actually my reception is ok, all green, but at that moment I had just started the receiver and it takes a bit to estabilice, I have copied an image below of the normal reception. I have attached my output.dat that has logos for services e230 and e90f, 

![image](https://user-images.githubusercontent.com/26838980/196008267-db7e989b-5124-433c-be05-5e7a635f72d2.png)
[output.zip](https://github.com/softsyst/qirx_issues/files/9793144/output.zip)

**Comment by salvaaod** [comment]
You can download a 3 minute dab iq file so that you can try the mux locally   https://wetransfer.com/downloads/2e80777658e9ad8986e56339ba2a799220221015214059/43b4c6acff249f6c7c7972e22eb90a8220221015214149/516641

I loaded with qirx 3.2.2 and while it works ok the logos are not still shown.

**Comment by softsyst** [comment]
Thanks for the file. I downloaded it and it plays. A very quick look shows the following:

No TIIs are transmitted (has nothing to do with the SPI),

As for the SPI:
- The EPG & Logos service starts
- 10 MOT objects are successfully decoded for about 15 seconds, with one packet sequence error in between.
- Afterwards every 18s  follows a "MOT packet sequence errors", until the end.

I'll have a closer look tomorrow.

**Comment by salvaaod** [comment]
Yes, that is correct, there is no TII since it is just a single transmitter, no TII needed, the EPG & Logos has 10 logo images, 5 per service e230 and e90f, not very sure about the packet sequence error since that is handled by ODR-dabmux, there is no epg info in the service, just the logos. I checked the logs and it does not give me ay further relevant info.

**Comment by andimik** [comment]
Let me also investigate with other tools next week. Could be a bug at Opendigitalradio as well.

**Comment by salvaaod** [comment]
Thanks, I will try with other SPI content, I am going to carry a BBC1 mux and load its epg/logos on the output.dat to see how it goes.

**Comment by softsyst** [comment]
Hi Salva,

I figured it out. here is your mux with the pictures:

![image](https://user-images.githubusercontent.com/51386375/196048170-a402642c-c824-46c4-a358-8fd5233ae6da.png)

These were the issues:
1. The packet sequence error is due to the fact, that the sequence is not continuously maintained. IMO an error in the software. The standard writes in 5.3.2.1 Packet header:
**Continuity index**: this 2-bit, modulo-4 counter shall be incremented by one for each successive packet in a
series having the same address. It provides the link between successive packets, carrying the same service
component, regardless of length.

Your counters do not behave like this. Sometimes it counts only 0,1,2,0.. with 3 missing, instead of 0,1,2,3,0.. etc. The sometimes missing 3 IMO contradicts the above statement from the Standard. As a workaround, I let it re-begin at 0 counter in this situation, and then it continues properly.

2. Possibly a flaw in my software
   During the processing of the datagroup an xml file is created from a binary file. While this works ok, your naming of the binary file is more than unusual, as it has the extension .xml. In all muxes which I tested that file had the extension .EIB. And qirx is looking for this extension. Maybe there is a generic way to find that binary file. I'll check it. In any case I would not recommend to give a binary file the extension .xml.

You provide the pictures in several sizes, which is ok. Qirx uses only the small ones and deletes the other ones. Maybe this will change, perhaps I'll show the large ones by doubleclick or similar, if the letters are so small that they are unreadable.

Best,

Clem

**Comment by salvaaod** [comment]
Thanks Clem, actually I am using Odr-dabmux & Odr-dabmod to create the mux following this set of tools and following this process:  https://wiki.opendigitalradio.org/How_to_configure_SPI_(Service_and_Programme_Information)_for_ODR-DabMux 

The first issue you mentioned is handled by Odr-dabmux and the second I guess is handled by the SPI file software, I will raise both issues in the ODR group. do you have plans to patch those two issues in QIRX dab decoder?

Thanks.
Salva

**Comment by softsyst** [comment]
Hi Salva,

I am not sure whether the workaround with the counter can do any harm in some other situation, thus I'll leave it in for the time being. In addition, there are two CRC checks, one with every packet and another one in the datagroup. None of these had triggered. In case of a packet loss (what I initially suspected), at least the datagroup CRC should have kicked in.

With the second issue, I hope to find a generic solution for the file extension problem. Then it would be a no-issue. However, I had looked in the standard, and did not find anything. But the always used .EHB and .EIB extensions are not in the standard either.

FYI, I attach the xml file generated by qirx here.

Clem
[1AE7EFDC.zip](https://github.com/softsyst/qirx_issues/files/9795488/1AE7EFDC.zip)

**Comment by salvaaod** [comment]
Thanks, I guess that this fix will be available when you do a new version,
or is it any other way to get the interim versión with the fix ?

Regarding the filename, I was wondering if either dabmux or the SPI file
generating tools are the ones to look for, is this name in the data sent in
the SPI channel? or is it in the FIC info ?

Thanks
Salva

**Comment by softsyst** [comment]
The 4.03 will be out very soon, within the next days. I'll leave everything as it is now, so your current mux should work with it.

**Comment by softsyst** [comment]
4.03 is out. I close this one
