### ISSUE TITLE
TII logger uses local time instead of recording date and time

### ISSUE THREAD

**Issue by andimik** [softsyst/qirx_issues#58]
When I load an xml file (recorded a while ago) into Qirx, the TII logger logs the local time instead of the recording date and time.

![grafik](https://user-images.githubusercontent.com/24510556/209565982-ce9ed895-659d-4da2-9817-4bf5339e04e4.png)

If the logger showed the recorded time instead, then it would be easier for test drive analysis.

**Comment by softsyst** [comment]
First of all, thanks for all of your inputs. I'll carefully go through them. However, any changes will probably take some time and therefore not be placed in the next version, but (thanks to input them here) will enter the queue and stay here until finally processed.

Recording time instead of local time certainly is a useful feature, which will be considered.

And -by far not least - all the best wishes for a Happy New Year!

**Comment by softsyst** [comment]
Fixed in 4.0.5
