### ISSUE TITLE
Station Logos don't map correctly from UK commercial SPI data

### ISSUE THREAD

**Issue by mrwish7** [softsyst/qirx_issues#72]
Hi Clem,

Sorry - I have another issue to report with some strange UK SPI data!

Some of the local commercial muxes here in the UK (those run by NOW digital) carry a "Station Logos" stream. I can receive this myself via the 12D Coventry multiplex.

QIRX seems to download and parse this data correctly - After 25 minutes I have around 200 logos in the SPI/Temp folder (this temp folder is a nice solution to previous partial data-sets in v4.0.5!) which relate to services on the 12D mux itself, as well as the two national UK muxes (D1 National 11D/12A and SDL 11A). This then parses, and I get XML files in a **SIdPool_E1** directory which seem to have image mapping for all of these services. However, the images themselves nearly all get deleted, with nothing displayed on any of the ensembles in QIRX.

A couple of the images are kept and go to an E1C1A5 directory, these seem to be logos relating to the SDL national multiplex, but C1A5 is the ensemble ID for West Wiltshire.

I've attached the SPI folders, and the QIRX log.

[SPI.zip](https://github.com/softsyst/qirx_issues/files/10528107/SPI.zip)
[qirx.logqirx.log-2023-01-28--14-17-19.txt](https://github.com/softsyst/qirx_issues/files/10528115/qirx.logqirx.log-2023-01-28--14-17-19.txt)

And here's a ~26 min raw dump of 12D, the file is 6.5GB, but it's long enough for the SPI data to successfully complete.

https://drive.google.com/file/d/1fYFLN96eo7S9-PnBiTHk4wg5hjQpDwOe/view?usp=sharing

Thanks again for all your great work,

Adam

**Comment by softsyst** [comment]
I can have a look tomorrow in the afternoon. Thanks for the large raw file. Just downloading.

**Comment by softsyst** [comment]
Hi Adam,

After some lengthy tests, I have a solution. Thanks again for your huge raw file. Without it, the solution would not have been possible. Let me explain:

The SPI info "Station Logos" transmitted in the 26 minutes of your file contains the logos of three multiplexes:
Coventry, EId E1-C18E
D1 National, EId E1-C181
SDL National, EId E1-C1CE

Thus, the "Coventry" Mux of which your file contains the audio, transmits the logos of the two other muxes as well. This is similar to the German case of the Federal Mux 5C "DR Deutschland" E0-10BC, which since some months transmits info for a number of services not belonging to that multiplex. However, in the xml info, there is some subtle difference, not plausible to me:

- Your mux transmits the ensemble id "EId" as the multiplex for the service which it contains. This seems plausible to me.
- On the other hand, in the German case, the EId info transmits the ensemble Id which is currently tuned, i.e. the E0-10BC. Thus the E0-10BC transmits his own EId for many service Ids which do not belong to it. Always the EId transmitted is in all cases the EId currently tuned which is E0-10BC.

These different solutions are confusing. My previous solution filtered everything with the EId currently tuned. As a result, everything worked for the German case but not for the English one.

 I went through the Standard and found out that the EId info  is completely redundant, as the Standard states that the service Id SId alone is (in combination with the Extended Country Code ECC) worldwide unique.

As a result, my solution now is the following:

All logos are collected in a directory of e.g. the SidPool_E1 (where E1 is the mentioned Extended Country Code for the UK), with subdirectories for every SId found in the transmission. The EId info also transmitted is discarded and remains only in the xml files which are stored as well. It is not used by qirx though.

This has the - nice - consequence that once your 26 minutes file has been completely run, all logos for the D1 National and the SDL National are displayed immediately, even if those muxes do not transmit logos themselves. If they did, these logos would addtionally be collected during their transmission. This is a case found in (another) German mux.

The solution of the "Pool" has been selected as there are services which are contained in different muxes. In Germany, such a case is the service "ANTENNE BAYERN", contained in the Ensemble 11D E0-10A5 "Bayern", as well as in the Ensemble 9B E0-11F7 "Antenne DE". 

All these different possibilities are more than confusing, but I now hope to come step by step to a solution covering all of them without any necessity for additional user interaction. 

Thanks again for your help!

Here I present some files which I have:

- The one which you recorded of the Coventry mux,

![image](https://user-images.githubusercontent.com/51386375/215517307-37ecbde0-4056-4db6-aac9-1f66feb3f851.png)

- Two other ones from my fundus, D1 National and SDL National, which themselves do not distribute SPI logos, but present them now thanks to your raw file.

![image](https://user-images.githubusercontent.com/51386375/215517700-e95384f2-6691-4a47-abc9-250a638e84f0.png)

![image](https://user-images.githubusercontent.com/51386375/215518320-9893e35c-6f41-4fc7-b19a-425cebfbb0a8.png)

And last not least, for all this to work the Error #71 reported by @nickpiggot needed to be repaired.
All this will soon come with the next update.

Best regards,
Clem

**Comment by mrwish7** [comment]
Thanks Clem, this seems like a very nice solution to have a common SID pool for each ECC, with the logos stored independently of the ensemble ID.

I’m glad the large raw file was useful for this! I’m looking forward to seeing it in the next update.

Kind regards,

Adam

**Comment by andimik** [comment]
@mrwish7

Adam, could you please leave the file online, I tried several times to download, but it failed. So I will use another network tomorrow.

Reason: I would like to test it with Qt-DAB which exports the SPI files as well.

**Comment by mrwish7** [comment]
@andimik Yes no problem, I will leave it online. Please just let me know when you've managed to download.

Thanks,

Adam

**Comment by softsyst** [comment]
Hi Adam,

please have a look whether it works in V4.0.6 or 4.0.7. Thanks!

**Comment by mrwish7** [comment]
> Hi Adam,
> 
> please have a look whether it works in V4.0.6 or 4.0.7. Thanks!

Hi Clem,

I confirm that it works perfectly in 4.0.6/4.0.7 - thanks for the fix!

<img width="960" alt="2023-02-19 (1)" src="https://user-images.githubusercontent.com/37659188/219973560-0f8cd3f9-4af1-40c5-b467-1ea998c088b8.png">
<img width="960" alt="2023-02-19 (2)" src="https://user-images.githubusercontent.com/37659188/219973563-873b29e6-f88f-4f52-b763-9ea3569d9ab6.png">
<img width="960" alt="2023-02-19 (3)" src="https://user-images.githubusercontent.com/37659188/219973564-7bff7dda-6f8b-4b4a-9ec7-984a41e5a4ed.png">
<img width="960" alt="2023-02-19" src="https://user-images.githubusercontent.com/37659188/219973566-aa6f4b50-fa9c-4806-823d-badadbf4f1ff.png">

Kind regards,
Adam

**Comment by softsyst** [comment]
Hello Adam,

Thanks for this good news! I close this issue.

Best,
Clem
