### ISSUE TITLE
EPG: Illogical behavior when the EPG is not up to date

### ISSUE THREAD

**Issue by edd-cgfan** [softsyst/qirx_issues#74]
Hi Clem,

please have a look at the EPG table: The German Bundesmux 1 on 5C doesn't broadcast an up to date EPG at the moment.
If one unchecks the "Today" checkbox the first available EPG from the drop down field is shown.
If you check the "Today" checkbox again then the old content remains in the table.
The image shows the table for DLF: Showing the EPG for Saturday January 14th.
![5C-EPG-not-up-to-date](https://user-images.githubusercontent.com/49753409/216151637-bcc14143-4163-48c9-a2c4-56569d188c93.PNG)

Regards,
cgfan

**Comment by softsyst** [comment]
Hi cgfan,

5C transmits EPG. I just tested it, but deleted the stored content beforehand. Please note that you have to wait at least 15-20 minutes before the EPG and logos are complete. For logos, it is no serious issue as during the collection also the old logos are used. This long time is due to the fact that this mux transmits also many icons for other muxes, like the Bumux2 and others.

However, if "Today" has been clicked without info available and then shows other dates, it is clearly an error. I hope I can repair it together with the other SPI errors which have been reported.

Due to this long waiting time, I think it would be good to have an indication when the info is complete.  This info is written in the log, but having to look into the log is of course no user-friendly solution.

Thanks for the report. Maybe you could make a check whether - after 20 minutes - the EPG info has become actual without having deleted the old info. If not, I'll have a look whether the old info is properly overwritten/enhanced.
I have currently no solution to avoid this long waiting time.

See also #72 with waiting times of almost half an hour. There it's less serious as only logos are affected, no EPG.

Clem

**Comment by edd-cgfan** [comment]
Hi Clem,

it seems that my former use cases didn't allow collecting and saving the EPG data because 5C wasn't tuned in long enough.
Thanks for the interesting information. Yes, I saw #72 also earlier.
I think it took about 35 minutes today and the EPG for Dlf was updated. I didn't have time to check it more precisely.
After changing service and coming back to Dlf the EPG info was updated. So it may have become actual earlier but it wasn't noticed.

> I think it would be good to have an indication when the info is complete.

That sounds good and hopefully it's not too complex to implement. 

Regards,
cgfan

**Comment by softsyst** [comment]
Please check if it's ok now in your opinion, in V4.0.6 or 4.0.7, Thanks!

**Comment by edd-cgfan** [comment]
Hi Clem,

just checked version 4.0.6: Works perfectly as intended.
I also had a look at the SPI collection time of the mdr mux on 6B here:
Since I was not at home, there was the last data taken on 2023-02-08 and EPG data until 2023-02-14:
It took about 14 minutes to collect the new data. EPG info is available until 2023-02-24.
I like reading EPGs...

Regards,
cgfan

**Comment by softsyst** [comment]
Thanks for feedback, cgfan! I'll close this one.

Best,
Clem
