### ISSUE TITLE
Saving Pictures from Slideshow

### ISSUE THREAD

**Issue by davidvisser1** [softsyst/qirx_issues#78]
At this moment during a session slideshowPictures are saved in directory.... \Pictures but all are gone after a new restart of the program.
Is it possible to code an option in Qirx to save them YES/NO. 

David Visser

**Comment by softsyst** [comment]
Thanks, David, for this useful suggestion. I'll check the effort for the next release. It won't be too much as I expect it.

Best,
Clem

**Comment by davidvisser1** [comment]
Hi Clem,
Have You already studied this issue ?

David Visser

**Comment by softsyst** [comment]
Hi David,

Yes, I did. Here is what I could consider.

These pictures are currently stored already in the "Pictures" directory (relative to the usual base directory, reachable by clicking the "Home" button), but deleted later on, in order not to litter the directory. Thus, currently only one picture is there usually. Omitting this "delete" and just let the pictures pile up, would be a small effort. However, as the number of pictures would grow, I assume some people would not be too happy with it. This was the case in the past, and as a result the old pictures were deleted.

Please note that currently its name is the CRC checksum of the pic, as this allows for a simple and unambiguous comparison, avoiding over and over storing the same picture again. There are many services using always the same (often useless) pictures, since many years btw.

A rather simple solution could be to add an entry in the config file indicating whether these pics should be deleted (i.e. the current solution) or not. Being part of the config file, this switch would be persisted . It could be made operable from a GUI checkbox, e.g. in the DAB "Service" tab where the pics show up.

Maybe you can leave a comment whether this would be sufficient for you. If not, it would be good to learn about your minimum requirements of the feature.

Regards,
Clem

**Comment by davidvisser1** [comment]
Hi Clem,

You wrote:
__**_**A rather simple solution could be to add an entry in the config file indicating whether these pics should be deleted (i.e. the current solution) or not. Being part of the config file, this switch would be persisted . It could be made operable from a GUI checkbox, e.g. in the DAB "Service" tab where the pics show up.**__**_

Yes Clem : A choice whether yes or not saving on the Gui (checkbox) would be fine !

David Visser

**Comment by softsyst** [comment]
Ok, I'll implement it in the described way.

**Comment by WIHDIA** [comment]
Great option imho.

73

Herman

Belgium editor [fmlist.org](https://www.fmlist.org)
[My logblog](https://www.wijnants.info/fmdx)

---

**Comment by softsyst** [comment]
Realized in 4.0.8

**Comment by softsyst** [comment]
Please have a look if the feature serves your needs. If so, I could close it here.

**Comment by davidvisser1** [comment]
All OK Clem.
Maybe You can change the name of the picture adding the channel nr in the name
5a  11b  etc

David  Visser

**Comment by softsyst** [comment]
Hi David,

This would be a little more effort, as in that case the name would no longer be unambiguous. I tried to avoid duplicates, and (to be honest) to implement a really simple solution.
But we can leave this issue open, and I have a look for the next version.

Best,
Clem

**Comment by softsyst** [comment]
Hello David,

Here is an example for the extended file name of these pictures, for the next version. The following image as an example:

![image](https://github.com/softsyst/qirx_issues/assets/51386375/ef072c41-3167-4370-b8ce-c4b4290f815b)

For this file the suggested filename would be:
11D-E0-10A5_Bayern-D314_BR-KLASSIK-BB3A184B.jpg

This means:
**Block No** (11D)-**ECC Id** (E0)-**EId** (10A5) _ **Ensemble Label** (Bayern)-**SId** (D314) _ **Service Label** (BR-KLASSIK)-**CRC** (BB3A1848).jpg

This file name should completely qualify the picture origin. The final id (CRC, 6 hexadecimal digits) is a unique number for the picture. This means if the identical picture shows up in another ensemble or service, it is not stored again.

I hope this will be ok for now.

Clem

**Edit**: 
One addition though: Taking the names of the ensemble and service into the file name is comfortable, but unfortunately the operators and service providers sometimes use names with illegal characters when used in a filename.

Consider the (real!) service label: "BAYERN 1 Nby/Opf". Apart from breaking your tongue, the slash is illegal in a windows file name. Therefore, it is replaced by an underscore in the software, to make it working. There may be a bunch of other characters which are not treated. All picture files with such illegal characters will not be saved. 

As trivial as it sounds, it is not, if one looks for a "clean" solution of the problem. BTW, the same holds for audio recording file names.

**Comment by softsyst** [comment]
Hi David,
could you please check whether the file names are ok in the V4.0.9? If so, I could close this one.
Thanks!

**Comment by davidvisser1** [comment]
Hi Clem,

Yes.  Names of the pictures are now better.
Thanks.

David Visser

------ Original Message ------
From "softsyst" ***@***.***>
To "softsyst/qirx_issues" ***@***.***>
Cc "davidvisser1" ***@***.***>; "Author" 
***@***.***>
Date 29-6-2023 22:21:04
Subject Re: [softsyst/qirx_issues] Saving Pictures from Slideshow (Issue 
#78)

**Comment by softsyst** [comment]
Thanks, David, I close it.
