### ISSUE TITLE
New feature suggestion: Add to the software a choise option for the "old" rtl_tcp and the new rtl2_tcp

### ISSUE THREAD

**Issue by schluckspecht** [softsyst/qirx_issues#80]
Hi
the most available SDRs are using the classical rtl2_tcp. But these do not work with rtl2_tcp. Therefore if you use also a 4.x version of Qirx, that does not support the old rtl_tcp any more, you have always to switch between the classical rtl_tcp and the rtl2_tcp. I use a remote rapsberry pi, that is located in the garden far away from electric noise to improve the reception. I have always to log in on the raspberry and switch the running rtl_tcp version. 

So it would be nice to habe both options in the Qirx SW.

**Comment by softsyst** [comment]
Hi,

thanks for mentioning this again. I am since some time aware of it.
The next version will have a possibility to select between the two. Not quite finished yet, some more tests are needed.

A similar case exist for the RSPs, the current RSP3_tcp is not generally usable. I'm thinking of it as well, but certainly not for the next qirx version.

Maybe other apps could be convinced by the users also to use e.g. rtl2_tcp, as it has many advantages. In the new rtl2_tcp, the possibility to make a selection if more than one dongle is connected is most welcome (for me at least).

As rtl_tcp is becoming more frequent (compared to rtl_sdr, my personal impression), maybe they could think about it. All is Open Source, rtl2_tcp from old-dab and RSP3_tcp (which uses the same protocol) from myself as well.

And just for the record (off -topic here), for the sdrplay RSPs there is a new version of RSP3_tcp with two releases on GitHub, one for Linux and one for Windows.

**Comment by softsyst** [comment]
Realized in the 4.0.8

**Comment by schluckspecht** [comment]
I wanted to test this new feature - I made the mistake to update. Now both licences do not work any more. I thought, they were bound to the machine - it is still the SAME computer.

**Comment by softsyst** [comment]
Of course the license codes continue to work after an update. Probably, you requested the installer to delete the config file. This creates a new config, of course with empty lic code. as that is the only place where it is stored. But if you saved the lic code it should work, after having entered in the "About". If it doesn't, please send me a PM with your code, and I check it. Should be no problem.

**Comment by softsyst** [comment]
No comments since two days. I close it. Please re-open if you find it necessary.

**Comment by schluckspecht** [comment]
The "old rtl_tcp" compatibility mode works perfectly. 👍 Thanks.

**Comment by softsyst** [comment]
Great! Thanks for feedback!
